POSTTEST 7

NAMA : Fanny Dita Ayunda Putri

NIM  : 2009106139

In [2]:
import numpy as np
import tensorflow as tf

In [3]:
random_tensor = tf.random.normal([5,5], mean=2., stddev=5., seed=1)
random_tensor.numpy()

array([[ -2.056591  ,   9.422994  ,   2.3266468 , -10.213521  ,
          2.496242  ],
       [  4.9561214 ,   4.964115  ,  -8.614648  ,  -1.6144862 ,
          1.7186481 ],
       [  5.217724  ,   0.67837965,  11.283166  ,   4.8392086 ,
          0.08582056],
       [ -5.426717  ,   8.308855  ,   1.8734696 ,   0.6768515 ,
          9.664069  ],
       [ -6.7148857 ,  -0.18946481,  -0.83005   ,   3.6033463 ,
          7.664155  ]], dtype=float32)

In [4]:
list_utt = [[1,5,7,9],[11,15,17,19],[21,25,27,29],[31,35,37,39],[41,45,47,49]]

utt = tf.convert_to_tensor(list_utt)
utt.numpy()

array([[ 1,  5,  7,  9],
       [11, 15, 17, 19],
       [21, 25, 27, 29],
       [31, 35, 37, 39],
       [41, 45, 47, 49]])

In [5]:
slicing = tf.random.normal([5,5,5])
slicing.numpy()

array([[[ 0.78275615,  0.5966545 , -0.47194836, -0.71575254,
          0.12844981],
        [-0.78193116, -2.3855624 ,  1.8920485 , -0.5722237 ,
         -1.4140924 ],
        [ 1.2217467 ,  0.9815783 , -1.1262436 ,  1.2255656 ,
          1.7110966 ],
        [-1.1979545 , -0.32096002, -0.5286871 ,  1.1826814 ,
          0.8855795 ],
        [-1.4306526 , -3.4361908 ,  1.7149858 , -0.19484234,
          1.0247941 ]],

       [[ 0.898293  ,  1.2740895 ,  1.5284954 ,  0.61521626,
          0.8784435 ],
        [ 1.2263372 ,  0.31663546,  0.03043338, -0.87407446,
          0.37618646],
        [ 0.4326596 ,  0.63368535,  0.09880315,  0.03275524,
         -2.6776507 ],
        [-0.05176039, -2.32762   ,  2.027987  , -0.17340957,
         -0.06563471],
        [-0.08375049,  2.748558  ,  0.74724925, -0.13758458,
         -0.25242913]],

       [[ 0.15644492,  1.9301356 ,  0.99504566,  0.6790811 ,
         -0.08978736],
        [ 0.59622604,  2.0816028 , -0.73367065, -0.6020559 ,
         -1

In [6]:
slicing[3,3,3]

<tf.Tensor: shape=(), dtype=float32, numpy=0.76288974>

In [7]:
tf.gather(slicing, indices=[3,3,3]).numpy()

array([[[ 0.7399482 ,  0.68120897, -1.3935423 ,  0.29422906,
          1.0763179 ],
        [ 0.7203929 ,  0.6487962 , -0.28776726, -0.76762867,
          0.8173639 ],
        [ 0.6280035 ,  0.22146587, -1.2916162 , -1.3391064 ,
          0.40493134],
        [ 2.2946117 ,  0.8595317 , -0.3653993 ,  0.76288974,
         -1.6423769 ],
        [ 2.002726  ,  0.371156  ,  1.2335889 , -0.42365924,
          0.6134027 ]],

       [[ 0.7399482 ,  0.68120897, -1.3935423 ,  0.29422906,
          1.0763179 ],
        [ 0.7203929 ,  0.6487962 , -0.28776726, -0.76762867,
          0.8173639 ],
        [ 0.6280035 ,  0.22146587, -1.2916162 , -1.3391064 ,
          0.40493134],
        [ 2.2946117 ,  0.8595317 , -0.3653993 ,  0.76288974,
         -1.6423769 ],
        [ 2.002726  ,  0.371156  ,  1.2335889 , -0.42365924,
          0.6134027 ]],

       [[ 0.7399482 ,  0.68120897, -1.3935423 ,  0.29422906,
          1.0763179 ],
        [ 0.7203929 ,  0.6487962 , -0.28776726, -0.76762867,
          0

In [8]:
tf.gather_nd(slicing, indices=[[0,2,2],[1,2,2],[2,2,2],[3,2,2],[4,2,2]]).numpy()

array([-1.1262436 ,  0.09880315,  0.27701122, -1.2916162 ,  2.3189776 ],
      dtype=float32)

Tensorflow Dengan Bilangan Prima

In [9]:
list_prime = [[2, 3, 5, 7, 11],[13, 17, 19, 23, 29],[31, 37, 41, 43, 47],[53, 59, 61, 71, 73],[79, 83, 89, 97, 1]]

prime_tensor = tf.constant(list_prime, dtype=tf.float32)
prime_tensor.numpy()

array([[ 2.,  3.,  5.,  7., 11.],
       [13., 17., 19., 23., 29.],
       [31., 37., 41., 43., 47.],
       [53., 59., 61., 71., 73.],
       [79., 83., 89., 97.,  1.]], dtype=float32)

Dimensi Pada ke-2 Variabel Diatas

In [10]:
prime_tensor.shape

TensorShape([5, 5])

In [11]:
random_tensor.shape

TensorShape([5, 5])

Penggabungan Variabel  Concatenation

In [12]:
tf.concat([random_tensor,prime_tensor], axis=1).numpy()#Penggabungan Variabel Pada Kolom

array([[-2.0565910e+00,  9.4229937e+00,  2.3266468e+00, -1.0213521e+01,
         2.4962420e+00,  2.0000000e+00,  3.0000000e+00,  5.0000000e+00,
         7.0000000e+00,  1.1000000e+01],
       [ 4.9561214e+00,  4.9641151e+00, -8.6146479e+00, -1.6144862e+00,
         1.7186481e+00,  1.3000000e+01,  1.7000000e+01,  1.9000000e+01,
         2.3000000e+01,  2.9000000e+01],
       [ 5.2177238e+00,  6.7837965e-01,  1.1283166e+01,  4.8392086e+00,
         8.5820556e-02,  3.1000000e+01,  3.7000000e+01,  4.1000000e+01,
         4.3000000e+01,  4.7000000e+01],
       [-5.4267168e+00,  8.3088551e+00,  1.8734696e+00,  6.7685151e-01,
         9.6640692e+00,  5.3000000e+01,  5.9000000e+01,  6.1000000e+01,
         7.1000000e+01,  7.3000000e+01],
       [-6.7148857e+00, -1.8946481e-01, -8.3004999e-01,  3.6033463e+00,
         7.6641550e+00,  7.9000000e+01,  8.3000000e+01,  8.9000000e+01,
         9.7000000e+01,  1.0000000e+00]], dtype=float32)

In [13]:
tf.concat([random_tensor,prime_tensor], axis=0).numpy()#Penggabungan Variabel Pada Baris

array([[-2.0565910e+00,  9.4229937e+00,  2.3266468e+00, -1.0213521e+01,
         2.4962420e+00],
       [ 4.9561214e+00,  4.9641151e+00, -8.6146479e+00, -1.6144862e+00,
         1.7186481e+00],
       [ 5.2177238e+00,  6.7837965e-01,  1.1283166e+01,  4.8392086e+00,
         8.5820556e-02],
       [-5.4267168e+00,  8.3088551e+00,  1.8734696e+00,  6.7685151e-01,
         9.6640692e+00],
       [-6.7148857e+00, -1.8946481e-01, -8.3004999e-01,  3.6033463e+00,
         7.6641550e+00],
       [ 2.0000000e+00,  3.0000000e+00,  5.0000000e+00,  7.0000000e+00,
         1.1000000e+01],
       [ 1.3000000e+01,  1.7000000e+01,  1.9000000e+01,  2.3000000e+01,
         2.9000000e+01],
       [ 3.1000000e+01,  3.7000000e+01,  4.1000000e+01,  4.3000000e+01,
         4.7000000e+01],
       [ 5.3000000e+01,  5.9000000e+01,  6.1000000e+01,  7.1000000e+01,
         7.3000000e+01],
       [ 7.9000000e+01,  8.3000000e+01,  8.9000000e+01,  9.7000000e+01,
         1.0000000e+00]], dtype=float32)

Perhitungan Aritmatika 2 Variabel

In [15]:
print("1. Penjumlahan :",tf.add(prime_tensor,random_tensor))
print("\n2. Pengurangan :",tf.subtract(prime_tensor,random_tensor))
print("\n3. Perkalian :",tf.multiply(prime_tensor,random_tensor))
print("\n4. Pembagian :",tf.divide(prime_tensor,random_tensor))
print("\n5. Pangkat :",tf.pow(prime_tensor,random_tensor))
print("\n6. Setara :",tf.equal(prime_tensor,random_tensor))
print("\n7. Tidak Setara :",tf.not_equal(prime_tensor,random_tensor))
print("\n8. Maximum :",tf.math.maximum(prime_tensor,random_tensor))
print("\n9. Minimum :",tf.math.minimum(prime_tensor,random_tensor))
print("\n10. Kuadrat Perbedaan :",tf.math.squared_difference(prime_tensor,random_tensor))

1. Penjumlahan : tf.Tensor(
[[-5.6591034e-02  1.2422994e+01  7.3266468e+00 -3.2135210e+00
   1.3496243e+01]
 [ 1.7956121e+01  2.1964115e+01  1.0385352e+01  2.1385513e+01
   3.0718649e+01]
 [ 3.6217724e+01  3.7678379e+01  5.2283165e+01  4.7839211e+01
   4.7085819e+01]
 [ 4.7573284e+01  6.7308853e+01  6.2873470e+01  7.1676849e+01
   8.2664070e+01]
 [ 7.2285110e+01  8.2810532e+01  8.8169952e+01  1.0060335e+02
   8.6641550e+00]], shape=(5, 5), dtype=float32)

2. Pengurangan : tf.Tensor(
[[ 4.056591  -6.4229937  2.6733532 17.21352    8.503757 ]
 [ 8.043879  12.035885  27.614647  24.614487  27.281351 ]
 [25.782276  36.32162   29.716835  38.16079   46.91418  ]
 [58.426716  50.691147  59.12653   70.32315   63.33593  ]
 [85.71489   83.18947   89.83005   93.39665   -6.664155 ]], shape=(5, 5), dtype=float32)

3. Perkalian : tf.Tensor(
[[  -4.113182   28.268982   11.633234  -71.494644   27.458662]
 [  64.42958    84.38995  -163.67831   -37.133183   49.840794]
 [ 161.74944    25.100048  462.6098   

Tampilan Hasil Sorting (Descending)

In [16]:
sort_prime_tensor2 = tf.argsort(prime_tensor, direction="DESCENDING")
sort_prime_tensor2.numpy()

array([[4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [4, 3, 2, 1, 0],
       [3, 2, 1, 0, 4]])

In [17]:
sort_random_tensor2 = tf.argsort(random_tensor, direction="DESCENDING")
sort_random_tensor2.numpy()

array([[1, 4, 2, 0, 3],
       [1, 0, 4, 3, 2],
       [2, 0, 3, 1, 4],
       [4, 1, 2, 3, 0],
       [4, 3, 1, 2, 0]])

In [18]:
sort_random_tensor1 = tf.sort(random_tensor, direction="DESCENDING")
sort_random_tensor1.numpy()

array([[  9.422994  ,   2.496242  ,   2.3266468 ,  -2.056591  ,
        -10.213521  ],
       [  4.964115  ,   4.9561214 ,   1.7186481 ,  -1.6144862 ,
         -8.614648  ],
       [ 11.283166  ,   5.217724  ,   4.8392086 ,   0.67837965,
          0.08582056],
       [  9.664069  ,   8.308855  ,   1.8734696 ,   0.6768515 ,
         -5.426717  ],
       [  7.664155  ,   3.6033463 ,  -0.18946481,  -0.83005   ,
         -6.7148857 ]], dtype=float32)

In [19]:
sort_prime_tensor1 = tf.sort(prime_tensor, direction="DESCENDING")
sort_prime_tensor1.numpy()

array([[11.,  7.,  5.,  3.,  2.],
       [29., 23., 19., 17., 13.],
       [47., 43., 41., 37., 31.],
       [73., 71., 61., 59., 53.],
       [97., 89., 83., 79.,  1.]], dtype=float32)